version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: symrecipe_app
    volumes:
      - .:/var/www/symrecipe
      - /var/www/symrecipe/node_modules # Monte le dossier node_modules
    ports:
      - "9000:9000"
    depends_on:
      - db
    environment:
      - XDEBUG_MODE=debug
      - XDEBUG_CONFIG=client_host=host.docker.internal client_port=9003

  db:
    image: mysql:8.0
    container_name: symrecipe_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: symrecipe
      MYSQL_USER: symrecipe_user
      MYSQL_PASSWORD: Welcome123
    ports:
      - "5555:3306" # Expose le port 3306 de MySQL sur le port 5555 de l'h√¥te
    volumes:
      - db_data:/var/lib/mysql

  nginx:
    image: nginx:latest
    container_name: symrecipe_nginx
    volumes:
      - .:/var/www/symrecipe
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8090:80"
    depends_on:
      - app

volumes:
  db_data:
